
title: Craig's Workshop
email: craig9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My workshop website. Come back regularly to see what I've been making and fixing.

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
