
title: "Craig's Workshop Stuff"
email: craig9@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love workshops and tools, and I love to make, fix and mod things.
  Come back regularly and check out what I've been working on.
  -- Craig Marshall

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - publish
